module.exports.GITHUB_TOKEN = "{{ githubmfachecker_github_token }}"
module.exports.GITHUB_ORG = "{{ githubmfachecker_github_organization }}"
module.exports.SLACK_TOKEN = "{{ githubmfachecker_slack_token }}"
module.exports.SLACK_CHANNEL = "{{ githubmfachecker_slack_channel }}"
module.exports.SLACK_LOG = "{{ githubmfachecker_slack_log }}"
